import { describe, expect, it } from 'vitest'
import {
  parseTimestamp,
  parseTranscript,
  segmentsToFullText,
  TranscriptParseError,
} from '@/lib/transcripts/parse'

describe('parseTimestamp', () => {
  it.each([
    ['00:00:00.000', 0],
    ['00:01:02.500', 62.5],
    ['01:00:00.000', 3600],
    ['00:00:04,250', 4.25],
    ['02:30', 150],
  ])('parses %s', (raw, expected) => {
    expect(parseTimestamp(raw)).toBe(expected)
  })

  it.each(['', 'not-a-time', '12', '00:00:00:000'])('rejects %s', (raw) => {
    expect(parseTimestamp(raw)).toBeUndefined()
  })
})

describe('parseTranscript · vtt', () => {
  it('parses cues, voice spans, and cue identifiers', () => {
    const vtt = [
      'WEBVTT',
      '',
      'NOTE this file was generated by the publisher',
      '',
      'cue-1',
      '00:00:00.000 --> 00:00:04.000',
      '<v Ben Gilbert>Welcome to Acquired.',
      '',
      '2',
      '00:00:04.000 --> 00:00:09.500 align:start position:50%',
      '<v David Rosenthal>The complete history &amp; strategy of',
      'Nvidia.',
    ].join('\n')

    const { segments, fullText } = parseTranscript(vtt, 'vtt')

    expect(segments).toEqual([
      { start: 0, end: 4, text: 'Welcome to Acquired.', speaker: 'Ben Gilbert' },
      {
        start: 4,
        end: 9.5,
        text: 'The complete history & strategy of Nvidia.',
        speaker: 'David Rosenthal',
      },
    ])
    expect(fullText).toBe(
      'Ben Gilbert: Welcome to Acquired.\nDavid Rosenthal: The complete history & strategy of Nvidia.',
    )
  })

  it('tolerates CRLF line endings and a BOM', () => {
    const vtt = '\uFEFFWEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nHello there\r\n'

    expect(parseTranscript(vtt, 'vtt').segments).toEqual([
      { start: 1, end: 2, text: 'Hello there' },
    ])
  })

  it('skips cues with unparseable timing rather than failing the file', () => {
    const vtt = [
      'WEBVTT',
      '',
      'garbage --> also-garbage',
      'dropped',
      '',
      '00:00:05.000 --> 00:00:06.000',
      'kept',
    ].join('\n')

    expect(parseTranscript(vtt, 'vtt').segments).toEqual([
      { start: 5, end: 6, text: 'kept' },
    ])
  })

  it('strips presentation tags and drops empty cues', () => {
    const vtt = ['WEBVTT', '', '00:00:01.000 --> 00:00:02.000', '<i></i>', '', '00:00:02.000 --> 00:00:03.000', '<b>real</b> text'].join('\n')

    expect(parseTranscript(vtt, 'vtt').segments).toEqual([
      { start: 2, end: 3, text: 'real text' },
    ])
  })

  it('returns an empty transcript for content that is not a cue file', () => {
    expect(parseTranscript('<html><body>not a transcript</body></html>', 'vtt')).toEqual({
      fullText: '',
      segments: [],
    })
  })

  it('never emits an end before its start', () => {
    const vtt = 'WEBVTT\n\n00:00:10.000 --> 00:00:05.000\nreversed'

    expect(parseTranscript(vtt, 'vtt').segments).toEqual([
      { start: 10, end: 10, text: 'reversed' },
    ])
  })
})

describe('parseTranscript · srt', () => {
  it('parses comma-decimal timings and numeric indices', () => {
    const srt = ['1', '00:00:00,000 --> 00:00:02,000', 'First line', '', '2', '00:00:02,000 --> 00:00:04,000', 'Second line'].join('\n')

    expect(parseTranscript(srt, 'srt').segments).toEqual([
      { start: 0, end: 2, text: 'First line' },
      { start: 2, end: 4, text: 'Second line' },
    ])
  })
})

describe('parseTranscript · json', () => {
  it('parses the podcast-namespace JSON format including speakers', () => {
    const json = JSON.stringify({
      version: '1.0.0',
      segments: [
        { speaker: 'Lenny', startTime: 0, endTime: 1.5, body: 'Hello' },
        { startTime: 1.5, endTime: 3, body: 'No speaker here' },
      ],
    })

    expect(parseTranscript(json, 'json').segments).toEqual([
      { start: 0, end: 1.5, text: 'Hello', speaker: 'Lenny' },
      { start: 1.5, end: 3, text: 'No speaker here' },
    ])
  })

  it('skips entries missing timing or body', () => {
    const json = JSON.stringify({
      segments: [
        { startTime: 0, body: 'no end' },
        { startTime: 1, endTime: 2, body: '   ' },
        { startTime: 2, endTime: 3, body: 'kept' },
      ],
    })

    expect(parseTranscript(json, 'json').segments).toEqual([
      { start: 2, end: 3, text: 'kept' },
    ])
  })

  it('throws on invalid JSON so the caller can fall through to the next source', () => {
    expect(() => parseTranscript('{not json', 'json')).toThrow(TranscriptParseError)
  })

  it('throws when the payload has no segments array', () => {
    expect(() => parseTranscript('{"version":"1.0.0"}', 'json')).toThrow(
      /no `segments` array/,
    )
  })
})

describe('parseTranscript · text', () => {
  it('keeps the text and reports no segments, because plain text carries no timing', () => {
    const text = 'First paragraph.\n\n  Second   paragraph.  \n'

    expect(parseTranscript(text, 'text')).toEqual({
      fullText: 'First paragraph.\nSecond paragraph.',
      segments: [],
    })
  })

  it('strips HTML markup, scripts, and entities', () => {
    const html = '<html><head><style>p{color:red}</style></head><body><p>Hello &amp; welcome</p><script>alert(1)</script><p>Second</p></body></html>'

    expect(parseTranscript(html, 'text').fullText).toBe('Hello & welcome\nSecond')
  })
})

describe('segmentsToFullText', () => {
  it('prefixes a speaker only when one is known', () => {
    expect(
      segmentsToFullText([
        { start: 0, end: 1, text: 'with', speaker: 'A' },
        { start: 1, end: 2, text: 'without' },
      ]),
    ).toBe('A: with\nwithout')
  })
})
